services:
  db:
    image: postgres:18-alpine
    container_name: openoffice_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openoffice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./PublicInit:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres_data: {}
