export const GET_CATEGORIES = "GET_CATEGORIES";
export const LIST_PANTRIES = "LIST_PANTRIES";
export const LIST_PANTRY_INVENTORY = "LIST_PANTRY_INVENTORY";
export const LIST_SUPPLIERS = "LIST_SUPPLIERS";
